name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./uilib/uilib
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - name: "install"
        run: yarn install --frozen-lockfile
        # working-directory: "./uilib"
      - name: "Unit Tests"
        run: yarn lib:test
        # working-directory: "./uilib"
      - name: "Test Build"
        run: yarn build:sb
        # working-directory: "./uilib"
